on: [push]

name: IoT_Dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        environment: 'AzureStack'
        enable-AzPSSession: true 
